export {
  db,
  withOrgContext,
  withUserContext,
  withUserAndOrgContext,
  forOrg,
  InvalidOrganizationIdError,
  InvalidUserIdError,
  type Prisma,
  type PrismaTransactionClient,
  type organizations,
  type users,
  type memberships,
  type invitations,
  type sessions,
  type refresh_tokens,
  type magic_link_tokens,
  type password_reset_tokens,
  type auth_events,
  type audit_events,
  type brands,
  type competitors,
  type brand_entities,
  type use_cases,
  type brand_claims,
  type claim_confidence,
  type role,
  type job_status,
  type job_type,
  type run_status,
  type subscription_status,
  // Epic 16 (Billing)
  type plans,
  type subscriptions,
  type usage_records,
  type usage_metric,
  type billing_webhook_events,
  // Epic 1 (CRM)
  type leads,
  type deals,
  type activities,
  type lead_source,
  type lead_status,
  type deal_stage,
  type activity_type,
  // Epic 17 (Free AI + SEO Growth Snapshot)
  type snapshot_requests,
  type snapshot_status,
  // Epic 5 (Intent & Query Universe)
  type query_sets,
  type queries,
  // Epic 3 (Website Intelligence)
  type crawl_jobs,
  type pages,
  type page_issues,
  type sitemaps,
  type crawl_status,
  type issue_type,
  type issue_severity,
  // Epic 4 (SEO Intelligence)
  type keyword_groups,
  type seo_keywords,
  type seo_analyses,
  type seo_opportunities,
  type keyword_intent,
  type seo_keyword_confidence,
  type seo_provider_source,
  type seo_analysis_type,
  type opportunity_status,
  // Epic 7 (AI Visibility Engine)
  type ai_runs,
  type ai_run_responses,
  type brand_observations,
  // Epic 9 (Opportunity Engine)
  type unified_opportunities,
  type opportunity_evidence,
  type unified_opportunity_type,
} from './client.js';
