export {
  db,
  withOrgContext,
  withUserContext,
  withUserAndOrgContext,
  forOrg,
  InvalidOrganizationIdError,
  InvalidUserIdError,
  type Prisma,
  type PrismaTransactionClient,
  type organizations,
  type users,
  type memberships,
  type invitations,
  type sessions,
  type refresh_tokens,
  type magic_link_tokens,
  type password_reset_tokens,
  type auth_events,
  type audit_events,
  type brands,
  type competitors,
  type brand_entities,
  type use_cases,
  type brand_claims,
  type claim_confidence,
  type role,
  type job_status,
  type job_type,
  type run_status,
  type subscription_status,
  // Epic 1 (CRM)
  type leads,
  type deals,
  type activities,
  type lead_source,
  type lead_status,
  type deal_stage,
  type activity_type,
  // Epic 5 (Intent & Query Universe)
  type query_sets,
  type queries,
  // Epic 3 (Website Intelligence)
  type crawl_jobs,
  type pages,
  type page_issues,
  type sitemaps,
  type crawl_status,
  type issue_type,
  type issue_severity,
} from './client.js';
